WebStore-master/Store/Models/Brand.cs
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Store.Models
{
    public class Brand
    {
        [Key]
        public int Id { get; set; }
        
        [Required]
        [Display(Name="Nazwa")]
        public string Name { get; set; }

        public string PhotoPath { get; set; }
        [Display(Name = "Logo")]
        [NotMapped]
        public IFormFile Photo { get; set; }

        [Display(Name = "Opis")]
        public string Description { get; set; }

        public virtual List<Product> Products { get; set; }
    }
}

WebStore-master/Store/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace Store.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Nazwa jest wymagana")]
        [Display(Name = "Nazwa")]
        public string Name { get; set; }

    }
}

WebStore-master/Store/Models/Color.cs
using System.ComponentModel.DataAnnotations;

namespace Store.Models
{
    public class Color
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name="Nazwa")]
        public string Name { get; set; }
    }
}

WebStore-master/Store/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Store.Models
{
    public class Order
    {
        public int Id { get; set; }
        public string ChargeId { get; set; }

        public bool IsSend { get; set; } = false;

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/DD/YYYY}")]
        [Required]
        public DateTime? OrderDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/DD/YYYY}")]
        public DateTime? OrderSendDate { get; set; } = null;

        [Required]
        [Display(Name = "Imię")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Nazwisko")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Adres 1")]
        public string Address1 { get; set; }

        [Display(Name = "Adres 2")]
        public string Address2 { get; set; }

        public string Email { get; set; }

        [Required]
        [Display(Name ="Miasto")]
        public string City { get; set; }

        [Required]
        [Display(Name = "Kod pocztowy")]
        public string PostCode { get; set; }

        public int? UserId { get; set; }
        public User User { get; set; }

        public ICollection<OrderProduct> OrderProducts{ get; set; }

    }
}

WebStore-master/Store/ViewModels/CreateRoleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Store.ViewModels
{
    public class CreateRoleViewModel
    {
        [Required]
        [Display(Name = "Nazwa")]
        public string RoleName { get; set; }
    }
}

WebStore-master/Store/Controllers/API/AdministrationController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Store.Models;
using System.Linq;

namespace Store.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class AdministrationController : ControllerBase
    {
        private readonly StoreContext _context;
        private readonly IMapper _mapper;


        public AdministrationController(StoreContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }


        [HttpDelete]
        [Route("{id:int}")]
        public IActionResult DeleteUser([FromRoute] int id)
        {
            var userInDb = _context.Users.SingleOrDefault(x => x.Id.Equals(id));

            if (userInDb == null)
            {
                return NotFound();
            }

            _context.Users.Remove(userInDb);
            _context.SaveChanges();

            System.Diagnostics.Debug.WriteLine("Usunieto usera");
            return Ok();
            
        }


        [HttpGet]
        public IActionResult GetUsers()
        {
            var users = _context.Users.ToList();

            return Ok(users);
        }


        [HttpGet]
        [Route("{id:int}")]
        public IActionResult GetUser([FromRoute] int id)
        {
            var userInDb = _context.Users.SingleOrDefault(c => c.Id.Equals(id));


            if (userInDb == null)
                return NotFound();

            return Ok(userInDb);
        }


        [HttpPost]
        public IActionResult PostUser([FromBody] User user)
        {
            _context.Users.Add(user);
            _context.SaveChanges();

            return Ok();
        }

    }
}

WebStore-master/Store/Controllers/API/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Store.Models;
using System.Threading.Tasks;

namespace Store.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class ProductController : ControllerBase
    {

        private readonly StoreContext _context;
        private readonly IMapper _mapper;

        public ProductController(StoreContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }


        [HttpGet]
        public async Task<IActionResult> Get()
        {
            var products = await _context.Products.ToListAsync();

            return Ok(products);
        }

        [HttpGet]
        [Route("{id:int}")]
        public async Task<IActionResult> GetProduct([FromRoute] int id)
        {
            var product = await _context.Products.SingleOrDefaultAsync(x => x.Id.Equals(id));

            return Ok(product);
        }

        [HttpPost]
        public async Task<IActionResult> Post([FromBody] Product product)
        {
            if (product == null)
            {
                return Conflict("Coś poszło nie tak");
            }


            _context.Products.Add(product);
            await _context.SaveChangesAsync();

            return Ok(product);

        }

        [HttpPut]
        public async Task<IActionResult> Put([FromBody] Product product)
        {
            var productInDb = await _context.Products.FirstOrDefaultAsync(x => x.Id == product.Id);

            if (productInDb == null)
            {
                return Conflict("Coś poszło nie tak");
            }

            _mapper.Map(product, productInDb);


            _context.Products.Update(productInDb);
            await _context.SaveChangesAsync();

            return Ok(product);

        }

        //[HttpDelete]
        //[Route("{id:int}")]

        //public async Task<IActionResult> DeleteProduct([FromRoute] int id)
        //{
        //    var productInDb = await _context.Products.SingleOrDefaultAsync(x => x.Id.Equals(id));

        //    if (productInDb == null)
        //    {
        //        return NotFound();
        //    }

        //    _context.Products.Remove(productInDb);
        //    await _context.SaveChangesAsync();

        //    return Ok();
        //}

        //[HttpDelete]
        //[Route("{id:int}")]

        //public async Task<IActionResult> DeleteStock(int id)
        //{
        //    var productInDb = await _context.Stock.SingleOrDefaultAsync(x => x.Id.Equals(id));

        //    if (productInDb == null)
        //    {
        //        return NotFound();
        //    }

        //    _context.Stock.Remove(productInDb);
        //    await _context.SaveChangesAsync();

        //    return Ok();
        //}
    }
}

WebStore-master/Store/Controllers/AdministrationController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Store.Models;
using Store.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Store.Controllers
{
    [Authorize(Roles ="Admin")]

    public class AdministrationController : Controller
    {

        private readonly RoleManager<Role> _roleManager;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IMapper _mapper;

        private readonly StoreContext _context;

        public AdministrationController(RoleManager<Role> roleManager, UserManager<User> userManager, StoreContext context,
            IWebHostEnvironment hostEnvironment, IMapper mapper, SignInManager<User> signInManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _signInManager = signInManager;
            _hostEnvironment = hostEnvironment;
            _mapper = mapper;
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> Users()
        {
            var users = await _context.Users.ToListAsync();

            if (_signInManager.IsSignedIn(User))
            {
                //zabezpieczenie aby admin nie mógł usunąć i edytować swojego konta będąc zalogowanym
                var userName = User.Identity.Name;
                var user = await _userManager.FindByNameAsync(userName);

                users.Remove(user);
            }

            return View(users);
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View(new CreateRoleViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = new Role
                {
                    Name = model.RoleName
                };

                var result = await _roleManager.CreateAsync(role);


                if (result.Succeeded)
                {
                    System.Diagnostics.Debug.WriteLine($"Stworzono role {model.RoleName}");

                    return RedirectToAction("Roles");
                }

                foreach (var error in result.Errors)
                {
                    System.Diagnostics.Debug.WriteLine($"Nieudana próba stworzenia roli {model.RoleName}");

                    ModelState.AddModelError("",error.Description);
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Roles()
        {
            var roles = _roleManager.Roles;

            return View(roles);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(int id)
        {
            var role = await _roleManager.FindByIdAsync(id.ToString());

            if (role==null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return NotFound();
            }

            var model = new EditRoleViewModel
            {
                Id = id,
                RoleName = role.Name,
                Users = new List<User>()
            };

            foreach (var user in await _userManager.GetUsersInRoleAsync(role.Name))
            {
                model.Users.Add(user);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.Id.ToString());

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                System.Diagnostics.Debug.WriteLine($"Nie znaleziono roli o id = {model.Id}");
                return NotFound();
            }

            role.Name = model.RoleName;
            var result = await _roleManager.UpdateAsync(role);

            if (result.Succeeded)
            {
                System.Diagnostics.Debug.WriteLine($"Edytowano rolę o id = {model.Id}");

                return RedirectToAction("ListRoles");
            }

            foreach (var error in result.Errors)
            {
                System.Diagnostics.Debug.WriteLine($"Nieudana rdycja roli o id = {model.Id}");

                ModelState.AddModelError("", error.Description);
            }

            model.Users = new List<User>();

            foreach (var user in await _userManager.GetUsersInRoleAsync(role.Name))
            {
                model.Users.Add(user);
            }
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(int roleId)
        {
            ViewBag.roleId = roleId;

            var role = await _roleManager.FindByIdAsync(roleId.ToString());

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                System.Diagnostics.Debug.WriteLine($"Nie znaleziono roli o id = {roleId}");

                return NotFound();
            }

            var model = new List<UserRoleViewModel>();

            var usersInRole = await _userManager.GetUsersInRoleAsync(role.Name);

            foreach (var user in _userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    IsSelected = await IsInRoleAsync(user,role.Name)
                };

                model.Add(userRoleViewModel);
            }

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, int roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId.ToString());

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                System.Diagnostics.Debug.WriteLine($"Nie znaleziono roli o id = {roleId}");
                return NotFound();
            }

            bool ifSucceeded = false;

            for (int i = 0; i < model.Count; i++)
            {
                var user = await _userManager.FindByIdAsync(model[i].UserId.ToString());

                if (model[i].IsSelected && !(await IsInRoleAsync(user, role.Name)))
                {
                    var result = await _userManager.AddToRoleAsync(user, role.Name);
                    if (result.Succeeded)
                    {
                        ifSucceeded = true;
                    }
                }
                else if (!model[i].IsSelected && await IsInRoleAsync(user, role.Name))
                {
                    ifSucceeded = await DeleteRoleAsync(user, role.Id);
                }

                if (ifSucceeded)
                {
                    if (i < model.Count - 1)
                    {
                        continue;
                    }
                    System.Diagnostics.Debug.WriteLine("Poprawne edytowano uzytkowników w roli");

                    return RedirectToAction("EditRole", new {id = roleId});
                }
            }

            return RedirectToAction("EditRole", new { id = roleId });
        }

        /// <summary>
        /// Własna implementacja sprawdzająca czy użytkownik znajduje się w danej roli
        /// </summary>
        /// <param name="user"></param>
        /// <param name="roleName"></param>
        /// <returns></returns>
        private async Task<bool> IsInRoleAsync(User user, string roleName)
        {
            var usersInRole = await _userManager.GetUsersInRoleAsync(roleName);

            foreach (var userInRole in usersInRole)
            {
                if (userInRole.Id == user.Id)
                {
                    return true;
                }
            }

            return false;
        }


        /// <summary>
        /// Własna implementacja usuwania użytkownika o danej roli
        /// </summary>
        /// <param name="user"></param>
        /// <param name="role"></param>
        /// <returns></returns>
        private async Task<bool> DeleteRoleAsync(User user, int roleId)
        {

            var userRole = new IdentityUserRole<int>
            {
                UserId = user.Id,
                RoleId = roleId
            };

            _context.UserRoles.Remove(userRole);
            await _context.SaveChangesAsync();


            return true;
        }


        [HttpGet]
        public async Task<IActionResult> UserDetails(int id)
        {
            var user = await _context.Users
                .Include(u => u.Gender)
                .SingleAsync(x => x.Id.Equals(id));


            return View(user);
        }


        /// <summary>
        /// Edycja użytkownika
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditUser(int id)
        {
            var user = await _context.Users
                .Include(x => x.Gender)
                .SingleOrDefaultAsync(x => x.Id.Equals(id));

            if (user == null)
                return NotFound();

            var viewModel = new UserFormViewModel
            {
                Genders = _context.Genders.ToList(),
                GenderId = user.GenderId,
                PhoneNumber = user.PhoneNumber,
                Id = user.Id,
                LastName = user.LastName,

WebStore-master/Store/Views/Administration/Brand.cshtml
@model IEnumerable<Store.Models.Brand>

@{
    ViewData["Title"] = "Index";
}


@{
    await Html.RenderPartialAsync("Partial/_nav_product");
}

<br />

<button type="button" class="btn btn-dark"
        onclick="location.href = '@Url.Action("AddBrand", "Administration")'">
    Dodaj nowy brand
</button>
<br />
<br />


<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Logo
            </th>
            <th>
                Edytuj
            </th>
            <th>
                Usuń
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <img src="~/images/@item.PhotoPath" alt="" height="30" />
            </td>
            <td>
                @Html.ActionLink("Edytuj", "EditBrand", new { id = item.Id })
            </td>
            <td>
                @Html.ActionLink("Usuń", "DeleteBrand", new { id = item.Id })
            </td>
        </tr>
        }
    </tbody>
</table>
<br />

WebStore-master/Store/Views/Administration/BrandForm.cshtml
@model Store.Models.Brand

@{
    ViewData["Title"] = "Formularz brandu";
}


@{ 
    await Html.RenderPartialAsync("Partial/_nav_product");
}

<hr />
<br />

<form id="myForm" enctype="multipart/form-data">

    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    <div class="form-row">

        <div class="form-group col-md-3">

            @Html.LabelFor(b => b.Name)
            @Html.TextBoxFor(b => b.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(b => b.Name)
        </div>

        <div class="col-md-2"></div>
        <div class="form-group col-md-6">

            @Html.LabelFor(b => b.Description)
            @Html.TextAreaFor(b => b.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(b => b.Description)
        </div>


    </div>
    <br />
    @{
        if (Model.Name == null)
        {

            <div class="form-row">
                <button id="save" type="button" value="Submit" class="btn btn-primary">Dodaj</button>
            </div>
        }
        else
        {
            @Html.HiddenFor(x => x.Id);

            <div class="form-row">
                <button id="save" type="button" value="Submit" class="btn btn-primary">Zapisz</button>
            </div>
        }
    }


    <div class="form-row">
        <div class="col-md-5"></div>



        <div class="form-group col-md-3">
            @{
                if (Model.PhotoPath == null)
                {
                    Model.PhotoPath = "ImageDefault.png";
                }
            }
            @Html.LabelFor(p => p.Photo)
            <div class="col-md-10">
                <img src="~/images/@Url.Content(Model.PhotoPath)" style="margin:10px" width="200" id="imagePreview" />
                <input id="imageBrowes" type="file" name="Photo" accept="image/jpeg, image/png" onchange="ShowImagePreview(this, document.getElementById('imagePreview'))" />
            </div>
        </div>
    </div>

    <br />
    <br />



</form>

<button type="button" class="btn btn-dark"
        onclick="location.href = '@Url.Action("Brand", "Administration")'">
    Wróć do listy
</button>



@section Scripts{

    <script src="~/js/main.js"></script>

<script>
    $(document).ready(function () {
        $('#save').click(function () {
            $.validator.unobtrusive.parse(myForm);
            if ($(myForm).valid()) {
                var file = $('#imageBrowes').get(0).files;
                var data = new FormData(myForm);
                data.append('Photo', file[0]);


                var ajaxConfig = {
                    type: "POST",
                    url: "/Administration/SaveBrand",
                    data: data,
                    success: function (response) {
                        window.location.replace("/Administration/Brand");
                    },
                    error: function (xhr, status) {
                        alert('Coś poszło nie tak :///');
                    }
                }

                if ($(myForm).attr('enctype') == "multipart/form-data") {
                    ajaxConfig["contentType"] = false;
                    ajaxConfig["processData"] = false;
                }

                $.ajax(ajaxConfig);
            }
        });
    });


</script>
}

WebStore-master/Store/Views/Administration/CategoryForm.cshtml
@model Store.Models.Category

@{
    ViewData["Title"] = "Formularz dodawania kategorii";
}

@{
    await Html.RenderPartialAsync("Partial/_nav_product");
}
<hr />
<br />


@using (Html.BeginForm("SaveCategory", "Administration"))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary()
    <div class="form-row">
        <div class="form-group col-md-4">
            @Html.LabelFor(x => x.Name)
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Name)
        </div>
    </div>

    <br />
    if (Model.Name == null)
    {
        <button type="submit" class="btn btn-primary">Dodaj nową kategorię</button>
    }
    else
    {
        @Html.HiddenFor(x=>x.Id)
        <button type="submit" class="btn btn-primary">Zapisz</button>

    }
}

<br />

<button type="button" class="btn btn-dark"
        onclick="location.href = '@Url.Action("Category", "Administration")'">
    Wróć do listy
</button>

WebStore-master/Store/Views/Administration/Color.cshtml
@model IEnumerable<Store.Models.Color>

@{
    ViewData["Title"] = "Color";
}
@{
    await Html.RenderPartialAsync("Partial/_nav_product");
}
<br />
<button type="button" class="btn btn-dark"
        onclick="location.href = '@Url.Action("AddColor", "Administration")'">
    Dodaj nowy kolor
</button>
<br />
<br />


<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Edytuj
            </th>
            <th>
                Usuń
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Edytuj", "EditColor", new { id = item.Id })
                </td>
                <td>
                    @Html.ActionLink("Usuń", "DeleteColor", new { id = item.Id })
                </td>

            </tr>
        }
    </tbody>
</table>

WebStore-master/Store/Views/Administration/ColorForm.cshtml
@model Store.Models.Color

@{
    ViewData["Title"] = "Formularz koloru";
}

@{
    await Html.RenderPartialAsync("Partial/_nav_product");
}
<hr />
<br />

@using (Html.BeginForm("SaveColor", "Administration"))
{
    @Html.AntiForgeryToken()

    <div class="text-danger">@Html.ValidationSummary()</div>
    <div class="form-row">
        <div class="form-group col-md-3">
            @Html.LabelFor(x => x.Name)
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Name)
        </div>
    </div>

    <br />
    {
        if (Model.Name == null)
        {
            <button type="submit" class="btn btn-primary">Dodaj nowy kolor</button>
        }
        else
        {
            @Html.HiddenFor(x=>x.Id)
            <button type="submit" class="btn btn-primary">Zapisz</button>

        }
    }
}
<br />

<button type="button" class="btn btn-dark"
        onclick="location.href = '@Url.Action("Color", "Administration")'">
    Wróć do listy
</button>

WebStore-master/Store/Views/Administration/Index.cshtml
@{
    ViewData["Title"] = "Index";
}


@{
    await Html.RenderPartialAsync("Partial/_nav_product");
}
    <style>
        body {
            justify-content: center;
            align-content: center;
            text-align: center
        }
    </style>

    <body>
        <img src="~/images//adminImage.png" alt="Alternate Text" style="display: inline-block; margin-top:100px" />
    </body>

WebStore-master/Store/Views/Administration/ProductForm.cshtml
@model Store.ViewModels.ProductFormViewModel

@{
    ViewData["Title"] = "Formularz produktu";
}

@{
    await Html.RenderPartialAsync("Partial/_nav_product");
}
<br />

@*<form enctype="multipart/form-data" asp-controller="Product" asp-action="AddProduct" method="post">*@
<form id="myForm" enctype="multipart/form-data">

    @Html.AntiForgeryToken()

    @Html.ValidationSummary()
    <div class="form-row">
        <div class="form-group col-md-2">
            @Html.LabelFor(p => p.CategoryId)
            @Html.DropDownListFor(p => p.CategoryId,
                new SelectList(Model.Categories, "Id", "Name")
                , new { @class = "form-control", @id = "drop-down-list-types" })
            @Html.ValidationMessageFor(p => p.CategoryId)
        </div>


        <div class="form-group col-md-2">

            @Html.LabelFor(p => p.BrandId)
            @Html.DropDownListFor(p => p.BrandId,
                new SelectList(Model.Brands, "Id", "Name")
                , new { @class = "form-control" })
            @Html.ValidationMessageFor(p => p.BrandId)

        </div>

        <div class="form-group col-md-2">

            @Html.LabelFor(p => p.ColorId)
            @Html.DropDownListFor(p => p.ColorId,
                new SelectList(Model.Colors, "Id", "Name")
                , new { @class = "form-control" })
            @Html.ValidationMessageFor(p => p.ColorId)
        </div>

        <div class="form-group col-md-2">

            @Html.LabelFor(p => p.SexId)
            @Html.DropDownListFor(p => p.SexId,
                new SelectList(Model.Sexes, "Id", "Name")
                , new { @class = "form-control" })
            @Html.ValidationMessageFor(p => p.SexId)

        </div>


    </div>
    <br />

    <div class="form-row">

        <div class="form-group col-md-4">

            @Html.LabelFor(p => p.Name)
            @Html.TextBoxFor(p => p.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(p => p.Name)

        </div>

    </div>
    <div class="form-row">

        <div class="form-group col-md-4">

            @Html.LabelFor(p => p.Description)
            @Html.TextAreaFor(p => p.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(p => p.Description)
        </div>

    </div>



    <div class="form-row">

        <div class="form-group col-md-1">
            @Html.LabelFor(p => p.Price)
            @Html.TextBoxFor(p => p.Price, new { @class = "form-control" })
            @*@Html.ValidationMessageFor(p => p.Price)*@
        </div>

    </div>
    <div class="form-row">
        @{
            if (Model.Id == 0)
            {
                <button id="save" type="button" value="Submit" class="btn btn-primary">Dodaj</button>
            }
            else
            {
                @Html.HiddenFor(x => x.Id)

                <button id="save" type="button" value="Submit" class="btn btn-primary">Zapisz</button>

            }
        }
    </div>

    <div class="form-row photo-container">
        <div class="col-md-6"></div>
        <div class="form-group col-md-3">
            @{
                if (Model.PhotoPath == null)
                {
                    Model.PhotoPath = "ImageDefault.png";
                }
            }
            @Html.LabelFor(p => p.Photo)
            <div class="col-md-10">
                <img src="~/images/@Url.Content(Model.PhotoPath)" style="margin:10px" width="200" id="imagePreview" />
                <input id="imageBrowes" type="file" name="Photo" accept="image/jpeg, image/png" onchange="ShowImagePreview(this, document.getElementById('imagePreview'))" />
            </div>
        </div>

    </div>


</form>
<br />

<button type="button" class="btn btn-dark"
        onclick="location.href = '@Url.Action("Products", "Administration")'">
    Wróć do listy
</button>


@section scripts{
    <script src="~/js/main.js"></script>
    <script>

        //Obsługa formularza
        $(document).ready(function () {
            $('#save').click(function () {
                $.validator.unobtrusive.parse(myForm);
                if ($(myForm).valid()) {
                    var file = $('#imageBrowes').get(0).files;
                    var data = new FormData(myForm);
                    data.append('Photo', file[0]);


                    var ajaxConfig = {
                        type: "POST",
                        url: "/Administration/SaveProduct",
                        data: data,
                        success: function (response) {
                            alert("Pomyślnie dodano!");
                        },
                        error: function (xhr, status) {
                            alert('Coś poszło nie tak :///');
                        }
                    }

                    if ($(myForm).attr('enctype') == "multipart/form-data") {
                        ajaxConfig["contentType"] = false;
                        ajaxConfig["processData"] = false;
                    }

                    $.ajax(ajaxConfig);
                }
            });
        });
    </script>

}

<style>

    #myForm{
        position:relative;
    }
    .photo-container{
        position:absolute;
        top:140px;
        right:150px;
    }
</style>